services:

  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - ${DATA_HOST_PATH}:/app/data
      - ${RESOURCES_HOST_PATH}:/app/resources

    ports:
      - "8000:8000"