services:
  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - ${DATA_HOST_PATH}:/app/data
      - ${RESOURCES_HOST_PATH}:/app/resources

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    environment:
      - PORT=3000
      - ORIGIN=http://localhost:3000

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${RESOURCES_HOST_PATH}:/mosquitto/config