/**
 * @file fe12.c
 *
 * @brief This source file was generated by cantools version 41.0.2 Mon Jan  5 08:42:36 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "fe12.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int fe12_vehicle_state_pack(
    uint8_t *dst_p,
    const struct fe12_vehicle_state_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->dashboard_hv_requested, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->dashboard_throttle1_level, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->dashboard_throttle2_level, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->dashboard_brake_level, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->dashboard_state, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->dashboard_vcu_ticks, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->dashboard_vcu_ticks, 0u, 0xffu);

    return (7);
}

int fe12_vehicle_state_unpack(
    struct fe12_vehicle_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->dashboard_hv_requested = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dashboard_throttle1_level = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->dashboard_throttle2_level = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->dashboard_brake_level = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->dashboard_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->dashboard_vcu_ticks = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->dashboard_vcu_ticks |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);

    return (0);
}

int fe12_vehicle_state_init(struct fe12_vehicle_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_vehicle_state_t));

    return 0;
}

uint8_t fe12_vehicle_state_dashboard_hv_requested_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_vehicle_state_dashboard_hv_requested_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_vehicle_state_dashboard_hv_requested_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_vehicle_state_dashboard_throttle1_level_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_vehicle_state_dashboard_throttle1_level_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_vehicle_state_dashboard_throttle1_level_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t fe12_vehicle_state_dashboard_throttle2_level_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_vehicle_state_dashboard_throttle2_level_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_vehicle_state_dashboard_throttle2_level_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t fe12_vehicle_state_dashboard_brake_level_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_vehicle_state_dashboard_brake_level_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_vehicle_state_dashboard_brake_level_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t fe12_vehicle_state_dashboard_state_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_vehicle_state_dashboard_state_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_vehicle_state_dashboard_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_vehicle_state_dashboard_vcu_ticks_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_vehicle_state_dashboard_vcu_ticks_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_vehicle_state_dashboard_vcu_ticks_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_bms_status_pack(
    uint8_t *dst_p,
    const struct fe12_bms_status_t *src_p,
    size_t size)
{
    uint8_t pei_communication_break_id;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->pei_bms_status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pei_spi_error_flags, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pei_spi_error_flags, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->pei_max_faulting_ic_address, 0u, 0xffu);
    pei_communication_break_id = (uint8_t)src_p->pei_communication_break_id;
    dst_p[4] |= pack_left_shift_u8(pei_communication_break_id, 0u, 0xffu);

    return (5);
}

int fe12_bms_status_unpack(
    struct fe12_bms_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t pei_communication_break_id;

    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->pei_bms_status = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->pei_spi_error_flags = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pei_spi_error_flags |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pei_max_faulting_ic_address = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    pei_communication_break_id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->pei_communication_break_id = (int8_t)pei_communication_break_id;

    return (0);
}

int fe12_bms_status_init(struct fe12_bms_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_bms_status_t));

    return 0;
}

uint8_t fe12_bms_status_pei_bms_status_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_bms_status_pei_bms_status_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_bms_status_pei_bms_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_bms_status_pei_spi_error_flags_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_bms_status_pei_spi_error_flags_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_bms_status_pei_spi_error_flags_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t fe12_bms_status_pei_max_faulting_ic_address_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_bms_status_pei_max_faulting_ic_address_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_bms_status_pei_max_faulting_ic_address_is_in_range(uint8_t value)
{
    return (value <= 9u);
}

int8_t fe12_bms_status_pei_communication_break_id_encode(double value)
{
    return (int8_t)(value);
}

double fe12_bms_status_pei_communication_break_id_decode(int8_t value)
{
    return ((double)value);
}

bool fe12_bms_status_pei_communication_break_id_is_in_range(int8_t value)
{
    return ((value >= -1) && (value <= 9));
}

int fe12_status_pack(
    uint8_t *dst_p,
    const struct fe12_status_t *src_p,
    size_t size)
{
    uint16_t pei_current_reference;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->pei_imd_ok, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->pei_bms_ok, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->pei_shutdown_final, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->pei_air_neg, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->pei_air_pos, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->pei_precharge, 0u, 0x01u);
    dst_p[1] |= pack_right_shift_u16(src_p->pei_current_adc, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pei_current_adc, 0u, 0xffu);
    pei_current_reference = (uint16_t)src_p->pei_current_reference;
    dst_p[3] |= pack_right_shift_u16(pei_current_reference, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(pei_current_reference, 0u, 0xffu);

    return (5);
}

int fe12_status_unpack(
    struct fe12_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pei_current_reference;

    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->pei_imd_ok = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->pei_bms_ok = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->pei_shutdown_final = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->pei_air_neg = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->pei_air_pos = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->pei_precharge = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->pei_current_adc = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pei_current_adc |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    pei_current_reference = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    pei_current_reference |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->pei_current_reference = (int16_t)pei_current_reference;

    return (0);
}

int fe12_status_init(struct fe12_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_status_t));

    return 0;
}

uint8_t fe12_status_pei_imd_ok_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_status_pei_imd_ok_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_status_pei_imd_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_status_pei_bms_ok_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_status_pei_bms_ok_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_status_pei_bms_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_status_pei_shutdown_final_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_status_pei_shutdown_final_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_status_pei_shutdown_final_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_status_pei_air_neg_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_status_pei_air_neg_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_status_pei_air_neg_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_status_pei_air_pos_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_status_pei_air_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_status_pei_air_pos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_status_pei_precharge_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_status_pei_precharge_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_status_pei_precharge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t fe12_status_pei_current_adc_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_status_pei_current_adc_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_status_pei_current_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t fe12_status_pei_current_reference_encode(double value)
{
    return (int16_t)(value);
}

double fe12_status_pei_current_reference_decode(int16_t value)
{
    return ((double)value);
}

bool fe12_status_pei_current_reference_is_in_range(int16_t value)
{
    return ((value >= -2048) && (value <= 2047));
}

int fe12_cooling_loop_temps_pack(
    uint8_t *dst_p,
    const struct fe12_cooling_loop_temps_t *src_p,
    size_t size)
{
    uint16_t telem_node_air_into_radiator_temp;
    uint16_t telem_node_air_out_of_radiator_temp;
    uint16_t telem_node_inlet_water_temp;
    uint16_t telem_node_outlet_water_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    telem_node_inlet_water_temp = (uint16_t)src_p->telem_node_inlet_water_temp;
    dst_p[0] |= pack_right_shift_u16(telem_node_inlet_water_temp, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(telem_node_inlet_water_temp, 0u, 0xffu);
    telem_node_outlet_water_temp = (uint16_t)src_p->telem_node_outlet_water_temp;
    dst_p[2] |= pack_right_shift_u16(telem_node_outlet_water_temp, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(telem_node_outlet_water_temp, 0u, 0xffu);
    telem_node_air_into_radiator_temp = (uint16_t)src_p->telem_node_air_into_radiator_temp;
    dst_p[4] |= pack_right_shift_u16(telem_node_air_into_radiator_temp, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(telem_node_air_into_radiator_temp, 0u, 0xffu);
    telem_node_air_out_of_radiator_temp = (uint16_t)src_p->telem_node_air_out_of_radiator_temp;
    dst_p[6] |= pack_right_shift_u16(telem_node_air_out_of_radiator_temp, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(telem_node_air_out_of_radiator_temp, 0u, 0xffu);

    return (8);
}

int fe12_cooling_loop_temps_unpack(
    struct fe12_cooling_loop_temps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t telem_node_air_into_radiator_temp;
    uint16_t telem_node_air_out_of_radiator_temp;
    uint16_t telem_node_inlet_water_temp;
    uint16_t telem_node_outlet_water_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    telem_node_inlet_water_temp = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    telem_node_inlet_water_temp |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->telem_node_inlet_water_temp = (int16_t)telem_node_inlet_water_temp;
    telem_node_outlet_water_temp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    telem_node_outlet_water_temp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->telem_node_outlet_water_temp = (int16_t)telem_node_outlet_water_temp;
    telem_node_air_into_radiator_temp = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    telem_node_air_into_radiator_temp |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->telem_node_air_into_radiator_temp = (int16_t)telem_node_air_into_radiator_temp;
    telem_node_air_out_of_radiator_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    telem_node_air_out_of_radiator_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->telem_node_air_out_of_radiator_temp = (int16_t)telem_node_air_out_of_radiator_temp;

    return (0);
}

int fe12_cooling_loop_temps_init(struct fe12_cooling_loop_temps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_cooling_loop_temps_t));

    return 0;
}

int16_t fe12_cooling_loop_temps_telem_node_inlet_water_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double fe12_cooling_loop_temps_telem_node_inlet_water_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_cooling_loop_temps_telem_node_inlet_water_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t fe12_cooling_loop_temps_telem_node_outlet_water_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double fe12_cooling_loop_temps_telem_node_outlet_water_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_cooling_loop_temps_telem_node_outlet_water_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t fe12_cooling_loop_temps_telem_node_air_into_radiator_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double fe12_cooling_loop_temps_telem_node_air_into_radiator_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_cooling_loop_temps_telem_node_air_into_radiator_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t fe12_cooling_loop_temps_telem_node_air_out_of_radiator_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double fe12_cooling_loop_temps_telem_node_air_out_of_radiator_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_cooling_loop_temps_telem_node_air_out_of_radiator_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int fe12_cool_loop_pressures_pack(
    uint8_t *dst_p,
    const struct fe12_cool_loop_pressures_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->telem_node_inlet_water_pressure, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->telem_node_inlet_water_pressure, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->telem_node_outlet_water_pressure, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->telem_node_outlet_water_pressure, 0u, 0xffu);

    return (4);
}

int fe12_cool_loop_pressures_unpack(
    struct fe12_cool_loop_pressures_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->telem_node_inlet_water_pressure = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->telem_node_inlet_water_pressure |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->telem_node_outlet_water_pressure = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->telem_node_outlet_water_pressure |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int fe12_cool_loop_pressures_init(struct fe12_cool_loop_pressures_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_cool_loop_pressures_t));

    return 0;
}

uint16_t fe12_cool_loop_pressures_telem_node_inlet_water_pressure_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double fe12_cool_loop_pressures_telem_node_inlet_water_pressure_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_cool_loop_pressures_telem_node_inlet_water_pressure_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t fe12_cool_loop_pressures_telem_node_outlet_water_pressure_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double fe12_cool_loop_pressures_telem_node_outlet_water_pressure_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_cool_loop_pressures_telem_node_outlet_water_pressure_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

int fe12_wheel_speed_rear_pack(
    uint8_t *dst_p,
    const struct fe12_wheel_speed_rear_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->telem_node_wheel_speed_rear_right, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->telem_node_wheel_speed_rear_right, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->telem_node_wheel_speed_rear_left, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->telem_node_wheel_speed_rear_left, 0u, 0xffu);

    return (4);
}

int fe12_wheel_speed_rear_unpack(
    struct fe12_wheel_speed_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->telem_node_wheel_speed_rear_right = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->telem_node_wheel_speed_rear_right |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->telem_node_wheel_speed_rear_left = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->telem_node_wheel_speed_rear_left |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int fe12_wheel_speed_rear_init(struct fe12_wheel_speed_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_wheel_speed_rear_t));

    return 0;
}

uint16_t fe12_wheel_speed_rear_telem_node_wheel_speed_rear_right_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_wheel_speed_rear_telem_node_wheel_speed_rear_right_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_wheel_speed_rear_telem_node_wheel_speed_rear_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_wheel_speed_rear_telem_node_wheel_speed_rear_left_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_wheel_speed_rear_telem_node_wheel_speed_rear_left_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_wheel_speed_rear_telem_node_wheel_speed_rear_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_torque_request_pack(
    uint8_t *dst_p,
    const struct fe12_torque_request_t *src_p,
    size_t size)
{
    uint16_t dashboard_torque;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dashboard_torque = (uint16_t)src_p->dashboard_torque;
    dst_p[0] |= pack_left_shift_u16(dashboard_torque, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(dashboard_torque, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->dashboard_speed, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->dashboard_speed, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->dashboard_direction, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->dashboard_inverter_enable, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->dashboard_discharge_enable, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->dashboard_speed_mode_enable, 2u, 0x04u);
    dst_p[6] |= pack_left_shift_u16(src_p->dashboard_torque_limit, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->dashboard_torque_limit, 8u, 0xffu);

    return (8);
}

int fe12_torque_request_unpack(
    struct fe12_torque_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t dashboard_torque;

    if (size < 8u) {
        return (-EINVAL);
    }

    dashboard_torque = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dashboard_torque |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->dashboard_torque = (int16_t)dashboard_torque;
    dst_p->dashboard_speed = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->dashboard_speed |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->dashboard_direction = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->dashboard_inverter_enable = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->dashboard_discharge_enable = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->dashboard_speed_mode_enable = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->dashboard_torque_limit = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->dashboard_torque_limit |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int fe12_torque_request_init(struct fe12_torque_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_torque_request_t));

    return 0;
}

int16_t fe12_torque_request_dashboard_torque_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double fe12_torque_request_dashboard_torque_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_torque_request_dashboard_torque_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_torque_request_dashboard_speed_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_torque_request_dashboard_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_torque_request_dashboard_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t fe12_torque_request_dashboard_direction_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_torque_request_dashboard_direction_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_torque_request_dashboard_direction_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_torque_request_dashboard_inverter_enable_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_torque_request_dashboard_inverter_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_torque_request_dashboard_inverter_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_torque_request_dashboard_discharge_enable_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_torque_request_dashboard_discharge_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_torque_request_dashboard_discharge_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_torque_request_dashboard_speed_mode_enable_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_torque_request_dashboard_speed_mode_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_torque_request_dashboard_speed_mode_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t fe12_torque_request_dashboard_torque_limit_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double fe12_torque_request_dashboard_torque_limit_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_torque_request_dashboard_torque_limit_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_random_shit_pack(
    uint8_t *dst_p,
    const struct fe12_random_shit_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u16(src_p->dashboard_front_strain_gauge, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->dashboard_front_strain_gauge, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->dashboard_front_wheel_speed, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->dashboard_front_wheel_speed, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->dashboard_tc_torque_request, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->dashboard_tc_torque_request, 0u, 0xffu);

    return (6);
}

int fe12_random_shit_unpack(
    struct fe12_random_shit_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->dashboard_front_strain_gauge = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->dashboard_front_strain_gauge |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->dashboard_front_wheel_speed = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->dashboard_front_wheel_speed |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->dashboard_tc_torque_request = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->dashboard_tc_torque_request |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int fe12_random_shit_init(struct fe12_random_shit_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_random_shit_t));

    return 0;
}

uint16_t fe12_random_shit_dashboard_front_strain_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_random_shit_dashboard_front_strain_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_random_shit_dashboard_front_strain_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_random_shit_dashboard_front_wheel_speed_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_random_shit_dashboard_front_wheel_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_random_shit_dashboard_front_wheel_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_random_shit_dashboard_tc_torque_request_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double fe12_random_shit_dashboard_tc_torque_request_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool fe12_random_shit_dashboard_tc_torque_request_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_diagnostic_bms_data_pack(
    uint8_t *dst_p,
    const struct fe12_diagnostic_bms_data_t *src_p,
    size_t size)
{
    uint16_t pei_pack_voltage;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->pei_hi_temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->pei_soc, 0u, 0xffu);
    pei_pack_voltage = (uint16_t)src_p->pei_pack_voltage;
    dst_p[2] |= pack_right_shift_u16(pei_pack_voltage, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(pei_pack_voltage, 0u, 0xffu);

    return (4);
}

int fe12_diagnostic_bms_data_unpack(
    struct fe12_diagnostic_bms_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pei_pack_voltage;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->pei_hi_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->pei_soc = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    pei_pack_voltage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    pei_pack_voltage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pei_pack_voltage = (int16_t)pei_pack_voltage;

    return (0);
}

int fe12_diagnostic_bms_data_init(struct fe12_diagnostic_bms_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_diagnostic_bms_data_t));

    return 0;
}

uint8_t fe12_diagnostic_bms_data_pei_hi_temp_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_diagnostic_bms_data_pei_hi_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_diagnostic_bms_data_pei_hi_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fe12_diagnostic_bms_data_pei_soc_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_diagnostic_bms_data_pei_soc_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_diagnostic_bms_data_pei_soc_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int16_t fe12_diagnostic_bms_data_pei_pack_voltage_encode(double value)
{
    return (int16_t)(value);
}

double fe12_diagnostic_bms_data_pei_pack_voltage_decode(int16_t value)
{
    return ((double)value);
}

bool fe12_diagnostic_bms_data_pei_pack_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int fe12_strain_gauges_rear_pack(
    uint8_t *dst_p,
    const struct fe12_strain_gauges_rear_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->telem_node_rl_toe_strain_gauge, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->telem_node_rl_toe_strain_gauge, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->telem_node_rluf_a_arm_strain_gauge, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->telem_node_rluf_a_arm_strain_gauge, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->telem_node_rlub_a_arm_strain_gauge, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->telem_node_rlub_a_arm_strain_gauge, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->telem_node_rllf_a_arm_strain_gauge, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->telem_node_rllf_a_arm_strain_gauge, 0u, 0xffu);

    return (8);
}

int fe12_strain_gauges_rear_unpack(
    struct fe12_strain_gauges_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->telem_node_rl_toe_strain_gauge = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->telem_node_rl_toe_strain_gauge |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->telem_node_rluf_a_arm_strain_gauge = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->telem_node_rluf_a_arm_strain_gauge |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->telem_node_rlub_a_arm_strain_gauge = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->telem_node_rlub_a_arm_strain_gauge |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->telem_node_rllf_a_arm_strain_gauge = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->telem_node_rllf_a_arm_strain_gauge |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int fe12_strain_gauges_rear_init(struct fe12_strain_gauges_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_strain_gauges_rear_t));

    return 0;
}

uint16_t fe12_strain_gauges_rear_telem_node_rl_toe_strain_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_strain_gauges_rear_telem_node_rl_toe_strain_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_strain_gauges_rear_telem_node_rl_toe_strain_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_strain_gauges_rear_telem_node_rluf_a_arm_strain_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_strain_gauges_rear_telem_node_rluf_a_arm_strain_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_strain_gauges_rear_telem_node_rluf_a_arm_strain_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_strain_gauges_rear_telem_node_rlub_a_arm_strain_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_strain_gauges_rear_telem_node_rlub_a_arm_strain_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_strain_gauges_rear_telem_node_rlub_a_arm_strain_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_strain_gauges_rear_telem_node_rllf_a_arm_strain_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_strain_gauges_rear_telem_node_rllf_a_arm_strain_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_strain_gauges_rear_telem_node_rllf_a_arm_strain_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_inputs_pack(
    uint8_t *dst_p,
    const struct fe12_inputs_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->dashboard_knob1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->dashboard_knob2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->dashboard_display_mode, 3u, 0x18u);
    dst_p[2] |= pack_left_shift_u8(src_p->dashboard_tc, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->dashboard_marker, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->dashboard_overtake, 0u, 0x01u);

    return (3);
}

int fe12_inputs_unpack(
    struct fe12_inputs_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->dashboard_knob1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dashboard_knob2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->dashboard_display_mode = unpack_right_shift_u8(src_p[2], 3u, 0x18u);
    dst_p->dashboard_tc = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->dashboard_marker = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->dashboard_overtake = unpack_right_shift_u8(src_p[2], 0u, 0x01u);

    return (0);
}

int fe12_inputs_init(struct fe12_inputs_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_inputs_t));

    return 0;
}

uint8_t fe12_inputs_dashboard_knob1_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_inputs_dashboard_knob1_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_inputs_dashboard_knob1_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t fe12_inputs_dashboard_knob2_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_inputs_dashboard_knob2_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_inputs_dashboard_knob2_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t fe12_inputs_dashboard_display_mode_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_inputs_dashboard_display_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_inputs_dashboard_display_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_inputs_dashboard_tc_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_inputs_dashboard_tc_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_inputs_dashboard_tc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_inputs_dashboard_marker_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_inputs_dashboard_marker_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_inputs_dashboard_marker_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t fe12_inputs_dashboard_overtake_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_inputs_dashboard_overtake_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_inputs_dashboard_overtake_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int fe12_current_pack(
    uint8_t *dst_p,
    const struct fe12_current_t *src_p,
    size_t size)
{
    uint16_t pei_current;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    pei_current = (uint16_t)src_p->pei_current;
    dst_p[0] |= pack_right_shift_u16(pei_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(pei_current, 0u, 0xffu);

    return (4);
}

int fe12_current_unpack(
    struct fe12_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pei_current;

    if (size < 4u) {
        return (-EINVAL);
    }

    pei_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    pei_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->pei_current = (int16_t)pei_current;

    return (0);
}

int fe12_current_init(struct fe12_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_current_t));

    return 0;
}

int16_t fe12_current_pei_current_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double fe12_current_pei_current_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_current_pei_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int fe12_high_level_bms_data_pack(
    uint8_t *dst_p,
    const struct fe12_high_level_bms_data_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->pei_hi_temp, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->pei_hi_temp, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->pei_pack_voltage, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->pei_pack_voltage, 0u, 0xffu);

    return (4);
}

int fe12_high_level_bms_data_unpack(
    struct fe12_high_level_bms_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->pei_hi_temp = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->pei_hi_temp |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->pei_pack_voltage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->pei_pack_voltage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int fe12_high_level_bms_data_init(struct fe12_high_level_bms_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_high_level_bms_data_t));

    return 0;
}

uint16_t fe12_high_level_bms_data_pei_hi_temp_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double fe12_high_level_bms_data_pei_hi_temp_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool fe12_high_level_bms_data_pei_hi_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_high_level_bms_data_pei_pack_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double fe12_high_level_bms_data_pei_pack_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_high_level_bms_data_pei_pack_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_bms_voltages_pack(
    uint8_t *dst_p,
    const struct fe12_bms_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->pei_subpack, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->pei_group, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->pei_voltage_1, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->pei_voltage_1, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->pei_voltage_2, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->pei_voltage_2, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->pei_voltage_3, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->pei_voltage_3, 0u, 0xffu);

    return (8);
}

int fe12_bms_voltages_unpack(
    struct fe12_bms_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->pei_subpack = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->pei_group = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->pei_voltage_1 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->pei_voltage_1 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pei_voltage_2 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->pei_voltage_2 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->pei_voltage_3 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->pei_voltage_3 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int fe12_bms_voltages_init(struct fe12_bms_voltages_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_bms_voltages_t));

    return 0;
}

uint8_t fe12_bms_voltages_pei_subpack_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_bms_voltages_pei_subpack_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_bms_voltages_pei_subpack_is_in_range(uint8_t value)
{
    return (value <= 4u);
}

uint8_t fe12_bms_voltages_pei_group_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_bms_voltages_pei_group_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_bms_voltages_pei_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint16_t fe12_bms_voltages_pei_voltage_1_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double fe12_bms_voltages_pei_voltage_1_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_bms_voltages_pei_voltage_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_bms_voltages_pei_voltage_2_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double fe12_bms_voltages_pei_voltage_2_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_bms_voltages_pei_voltage_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_bms_voltages_pei_voltage_3_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double fe12_bms_voltages_pei_voltage_3_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool fe12_bms_voltages_pei_voltage_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_bms_temps_pack(
    uint8_t *dst_p,
    const struct fe12_bms_temps_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->pei_subpack, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->pei_group, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->pei_temp_1, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->pei_temp_1, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->pei_temp_2, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->pei_temp_2, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->pei_temp_3, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->pei_temp_3, 0u, 0xffu);

    return (8);
}

int fe12_bms_temps_unpack(
    struct fe12_bms_temps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->pei_subpack = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->pei_group = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->pei_temp_1 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->pei_temp_1 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pei_temp_2 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->pei_temp_2 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->pei_temp_3 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->pei_temp_3 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int fe12_bms_temps_init(struct fe12_bms_temps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_bms_temps_t));

    return 0;
}

uint8_t fe12_bms_temps_pei_subpack_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_bms_temps_pei_subpack_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_bms_temps_pei_subpack_is_in_range(uint8_t value)
{
    return (value <= 4u);
}

uint8_t fe12_bms_temps_pei_group_encode(double value)
{
    return (uint8_t)(value);
}

double fe12_bms_temps_pei_group_decode(uint8_t value)
{
    return ((double)value);
}

bool fe12_bms_temps_pei_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint16_t fe12_bms_temps_pei_temp_1_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double fe12_bms_temps_pei_temp_1_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool fe12_bms_temps_pei_temp_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_bms_temps_pei_temp_2_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double fe12_bms_temps_pei_temp_2_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool fe12_bms_temps_pei_temp_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_bms_temps_pei_temp_3_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double fe12_bms_temps_pei_temp_3_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool fe12_bms_temps_pei_temp_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int fe12_shock_angles_rear_pack(
    uint8_t *dst_p,
    const struct fe12_shock_angles_rear_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->telem_node_rl_shock_angle, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->telem_node_rl_shock_angle, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->telem_node_rr_shock_angle, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->telem_node_rr_shock_angle, 0u, 0xffu);

    return (4);
}

int fe12_shock_angles_rear_unpack(
    struct fe12_shock_angles_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->telem_node_rl_shock_angle = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->telem_node_rl_shock_angle |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->telem_node_rr_shock_angle = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->telem_node_rr_shock_angle |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int fe12_shock_angles_rear_init(struct fe12_shock_angles_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_shock_angles_rear_t));

    return 0;
}

uint16_t fe12_shock_angles_rear_telem_node_rl_shock_angle_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_shock_angles_rear_telem_node_rl_shock_angle_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_shock_angles_rear_telem_node_rl_shock_angle_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t fe12_shock_angles_rear_telem_node_rr_shock_angle_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_shock_angles_rear_telem_node_rr_shock_angle_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_shock_angles_rear_telem_node_rr_shock_angle_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int fe12_raw_throttle_pack(
    uint8_t *dst_p,
    const struct fe12_raw_throttle_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->dashboard_throttle_1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->dashboard_throttle_1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->dashboard_throttle_2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->dashboard_throttle_2, 0u, 0xffu);

    return (4);
}

int fe12_raw_throttle_unpack(
    struct fe12_raw_throttle_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->dashboard_throttle_1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->dashboard_throttle_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->dashboard_throttle_2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->dashboard_throttle_2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int fe12_raw_throttle_init(struct fe12_raw_throttle_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fe12_raw_throttle_t));

    return 0;
}

uint16_t fe12_raw_throttle_dashboard_throttle_1_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_raw_throttle_dashboard_throttle_1_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_raw_throttle_dashboard_throttle_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t fe12_raw_throttle_dashboard_throttle_2_encode(double value)
{
    return (uint16_t)(value);
}

double fe12_raw_throttle_dashboard_throttle_2_decode(uint16_t value)
{
    return ((double)value);
}

bool fe12_raw_throttle_dashboard_throttle_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
